### ISSUE TITLE
iec-60870-5-104 Server simulator error

### ISSUE THREAD

**Issue by guo-sj** [FreyrSCADA/IEC-60870-5-104#2]
Hi, FreyrSCADA team.

I got the following error when pressing the button of **Add Server** in IEC-60870-5-104 Server Simulator:
![image](https://user-images.githubusercontent.com/31785247/139630756-d2b5010b-63f2-45d9-8570-17deded2414f.png)

I have no idea how to solve it, and any help will be appreciated.

**Comment by FreyrSCADA** [comment]
please try our latest version - https://github.com/FreyrSCADA/IEC-60870-5-104/blob/master/IEC%20104%20RTU%20Server%20Simulator/IEC104ServerSim.zip
