### ISSUE TITLE
M_IT_TB_1 37 Integrated totals with time tag CP56Time2a

### ISSUE THREAD

**Issue by zhangbaida888** [FreyrSCADA/IEC-60870-5-104#3]
In the latest version, (M_IT_TB_1 37 Integrated totals) Why only the first point data can be parsed correctly, while the rest are parsing errors.

[log_1.txt](https://github.com/FreyrSCADA/IEC-60870-5-104/files/11741359/log_1.txt)
[traffic_1.txt](https://github.com/FreyrSCADA/IEC-60870-5-104/files/11741360/traffic_1.txt)

**Comment by FreyrSCADA** [comment]
sure, we will check it and mail to you. can share the wireshare, it will be very useful to solve this.

**Comment by zhangbaida888** [comment]
Tested the new version again and the error persisted.


[(M_IT_TB_1)Counter type data display error.zip](https://github.com/FreyrSCADA/IEC-60870-5-104/files/11917741/M_IT_TB_1.Counter.type.data.display.error.zip)

**Comment by zhangbaida888** [comment]
> sure, we will check it and mail to you. can share the wireshare, it will be very useful to solve this.

@FreyrSCADA

**Comment by FreyrSCADA** [comment]
Hi , thank you for your response. i checked the protocol specification.

For M_IT_TB_1 , "Since each integrated total has its individual time tag, this type of ASDU does not exist as a
sequence of information elements."


so , Please check with the IEC 104 server provider. thank you

**Comment by zhangbaida888** [comment]
Thank you for your reply. I found a relevant document description, I do not know if it is the same as the 60870 standard.
@FreyrSCADA 

![IEC 60870-5-104_Ver1 3](https://github.com/FreyrSCADA/IEC-60870-5-104/assets/104166325/fa80f12d-cce9-40bb-9e65-fbcf5c74b976)
