### ISSUE TITLE
why not allow

### ISSUE THREAD

**Issue by runner-ccl** [FreyrSCADA/IEC-60870-5-104#5]
![屏幕截图 2024-01-10 164445](https://github.com/FreyrSCADA/IEC-60870-5-104/assets/35052472/66219d7d-340a-450a-bdf4-7e2595ce7a38)

**Comment by FreyrSCADA** [comment]
send a email to freyrscada@gmail.com

**Comment by FreyrSCADA** [comment]
send a email to [freyrscada@gmail.com](mailto:freyrscada@gmail.com)
